# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "All" %}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pyprojroot
  {% endif %}
  - python={{ cookiecutter.python_version }}
  - pip
  - pip:
    {% if cookiecutter.project_packages == "All" %}
    - pyhere
    {% endif %}



